export enum MaterialEnum {
  MATERIAL = "INGREDIENT",
  ACCESSORY = "ACCESSOR",
}

export enum MaterialStatus {
  AVAILABLE_IN_STOCK = "AVAILABLE_IN_STOCK",
  SENDING_REQUEST = "SENDING_REQUEST",
  CANCELLED = "CANCELLED",
}
